swagger: '2.0'
info:
  version: '1.0.0-beta'
  title: Analytics Pageview API
  description: Analytics Pageview API
  termsofservice: https://github.com/wikimedia/restbase#restbase
  contact:
    name: Analytics
    email: analytics@lists.wikimedia.org
    url: https://www.mediawiki.org/wiki/Analytics
  license:
    name: Apache licence, v2
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /pageviews/:
    get:
      tags:
        - Pageviews data
      summary: List pageview-related API entry points.
      description: |
        This is the root of all pageview data endpoints.  The list of paths that this returns includes ways to query by article, project, top articles, etc.  If browsing the interactive documentation, see the specifics for each endpoint below.

        Stability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Stable)
      produces:
        - application/json
      responses:
        '200':
          description: The queriable sub-items
          schema:
            $ref: '#/definitions/listing'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-monitor: false

  /pageviews/per-article/{project}/{access}/{agent}/{article}/{granularity}/{start}/{end}:
    get:
      tags:
        - Pageviews data
      summary: Get pageview counts for a page.
      description: |
        Given a Mediawiki article and a date range, returns a daily timeseries of its pageview counts. You can also filter by access method and/or agent type
        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)
      produces:
        - application/json
      parameters:
        - name: project
          in: path
          description: The name of any Wikimedia project formatted like {language code}.{project name}, for example en.wikipedia. You may pass en.wikipedia.org and the .org will be stripped off.  For projects like commons without language codes, use commons.wikimedia
          type: string
          required: true
        - name: access
          in: path
          description: If you want to filter by access method, use one of desktop, mobile-app or mobile-web. If you are interested in pageviews regardless of access method, use all-access
          type: string
          enum: ['all-access', 'desktop', 'mobile-app', 'mobile-web']
          required: true
        - name: agent
          in: path
          description: If you want to filter by agent type, use one of user, bot or spider. If you are interested in pageviews regardless of agent type, use all-agents
          type: string
          enum: ['all-agents', 'user', 'spider', 'bot']
          required: true
        - name: article
          in: path
          description: 'The name of any article in the specified project. Any spaces should be replaced with underscores. It also should be URI-encoded, so that non-URI-safe characters like %, / or ? are accepted. Example: Are_You_the_One%3F'
          type: string
          required: true
        - name: granularity
          in: path
          description: The time unit for the response data. As of today, the only supported granularity for this endpoint is daily
          type: string
          enum: ['daily']
          required: true
        - name: start
          in: path
          description: The date of the first day to include, in YYYYMMDD format
          type: string
          required: true
        - name: end
          in: path
          description: The date of the last day to include, in YYYYMMDD format
          type: string
          required: true
      responses:
        '200':
          description: The list of values
          schema:
            $ref: '#/definitions/article'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri: '{{options.host}}/pageviews/per-article/{project}/{access}/{agent}/{article}/{granularity}/{start}/{end}'
      x-monitor: false

  /pageviews/aggregate/{project}/{access}/{agent}/{granularity}/{start}/{end}:
    get:
      tags:
        - Pageviews data
      summary: Get pageview counts for a project.
      description: |
        Given a date range, returns a timeseries of pageview counts. You can filter by project, access method and/or agent type. You can choose between daily and hourly granularity as well
        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)
      produces:
        - application/json
      parameters:
        - name: project
          in: path
          description: If you want to filter by project, use the name of any Wikimedia project formatted like {language code}.{project name}, for example en.wikipedia. You may pass en.wikipedia.org and the .org will be stripped off. For projects like commons without language codes, use commons.wikimedia. If you are interested in all pageviews regardless of project, use all-projects
          type: string
          required: true
        - name: access
          in: path
          description: If you want to filter by access method, use one of desktop, mobile-app or mobile-web. If you are interested in pageviews regardless of access method, use all-access
          type: string
          enum: ['all-access', 'desktop', 'mobile-app', 'mobile-web']
          required: true
        - name: agent
          in: path
          description: If you want to filter by agent type, use one of user, bot or spider. If you are interested in pageviews regardless of agent type, use all-agents
          type: string
          enum: ['all-agents', 'user', 'spider', 'bot']
          required: true
        - name: granularity
          in: path
          description: The time unit for the response data. As of today, the supported granularities for this endpoint are hourly, daily, and monthly
          type: string
          enum: ['hourly', 'daily', 'monthly']
          required: true
        - name: start
          in: path
          description: The timestamp of the first day to include, in YYYYMMDDHH format
          type: string
          required: true
        - name: end
          in: path
          description: The timestamp of the first day to include, in YYYYMMDDHH format
          type: string
          required: true
      responses:
        '200':
          description: The list of values
          schema:
            $ref: '#/definitions/project'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri: '{{options.host}}/pageviews/aggregate/{project}/{access}/{agent}/{granularity}/{start}/{end}'
      x-monitor: true
      x-amples:
        - title: Get aggregate page views
          request:
            params:
              domain: wikimedia.org
              project: en.wikipedia
              access: all-access
              agent: all-agents
              granularity: hourly
              start: 1970010100
              end: 1970010100
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              items:
                - project: en.wikipedia
                  access: all-access
                  agent: all-agents
                  granularity: hourly
                  timestamp: 1970010100
                  views: 0

  /pageviews/top/{project}/{access}/{year}/{month}/{day}:
    get:
      tags:
        - Pageviews data
      summary: Get the most viewed articles for a project.
      description: |
        Lists the 1000 most viewed articles for a given project and timespan (year, month or day). You can filter by access method
        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)
      produces:
        - application/json
      parameters:
        - name: project
          in: path
          description: The name of any Wikimedia project formatted like {language code}.{project name}, for example en.wikipedia. You may pass en.wikipedia.org and the .org will be stripped off.  For projects like commons without language codes, use commons.wikimedia
          type: string
          required: true
        - name: access
          in: path
          description: If you want to filter by access method, use one of desktop, mobile-app or mobile-web. If you are interested in pageviews regardless of access method, use all-access
          type: string
          enum: ['all-access', 'desktop', 'mobile-app', 'mobile-web']
          required: true
        - name: year
          in: path
          description: The year of the date for which to retrieve top articles, in YYYY format. If you want to get the top articles of a whole year, the month and day parameters should be all-months and all-days respectively
          type: string
          required: true
        - name: month
          in: path
          description: The month of the date for which to retrieve top articles, in MM format. If you want to get the top articles of a whole month, the day parameter should be all-days.
          type: string
          required: true
        - name: day
          in: path
          description: The day of the date for which to retrieve top articles, in DD format.
          type: string
          required: true
      responses:
        '200':
          description: The list of top articles in the project
          schema:
            $ref: '#/definitions/tops'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri: '{{options.host}}/pageviews/top/{project}/{access}/{year}/{month}/{day}'
      x-monitor: false

definitions:
  # A https://tools.ietf.org/html/draft-nottingham-http-problem
  problem:
    required:
      - type
    properties:
      type:
        type: string
      title:
        type: string
      detail:
        type: string
      instance:
        type: string

  listing:
    description: The result format for listings
    required:
      - items
    properties:
      items:
        type: array
        items:
          type: string

  article:
    properties:
      items:
        type: array
        items:
          properties:
            project:
              type : string
            access:
              type : string
            article:
              type: string
            agent:
              type: string
            granularity:
              type: string
            timestamp:
              # the hourly timestamp will be stored as YYYYMMDDHH
              type: string
            views:
              type: integer
              format: int64

  project:
    properties:
      items:
        type: array
        items:
          properties:
            project:
              type : string
            access:
              type : string
            agent:
              type: string
            granularity:
              type: string
            timestamp:
              # the hourly timestamp will be stored as YYYYMMDDHH
              type: string
            views:
              type: integer
              format: int64

  tops:
    properties:
      items:
        type: array
        items:
          properties:
            project:
              type: string
            access:
              type : string
            year:
              type: string
            month:
              type: string
            day:
              type: string
            articles:
              # format for this is a json array: [{rank: 1, article: <<title>>, views: 123}, ...]
              type: string
