openapi: 3.0.1
info:
  version: 1.0.0-beta
  title: MediaWiki PDF API
  description: Page PDF Render API
  termsOfService: https://github.com/wikimedia/restbase#restbase
  contact:
    name: Services
    email: services@lists.wikimedia.org
    url: https://www.mediawiki.org/wiki/Services
  license:
    name: Apache licence, v2
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /pdf/{title}:
    x-route-filters: &pdf_get_title_filters
      - path: ./lib/access_check_filter.js
        options:
          redirect_cache_control: '{{options.cache_control}}'
      - type: default
        name: ratelimit_route
        options:
          limits:
            internal: 5
            external: 1
    get: &pdf_get_title_spec
      tags:
        - Page content
      summary: Get a page as PDF
      description: |
        Renders the page content as PDF. Format and type are optional parameters and
        the default values are "a4" for format and "desktop" for type.

        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)
      parameters:
        - name: title
          in: path
          description: 'Page title. Use underscores instead of spaces. Example: `Main_Page`.'
          required: true
          schema:
            type: string
      responses:
        200:
          description: The PDF render of an article
          headers:
            ETag:
              description: |
                Syntax: "{revision}/{tid}". Example: "701384379/154d7bca-c264-11e5-8c2f-1b51b33b59fc"
              schema:
                type: string
          content:
            application/pdf:
              schema:
                type: string
        404:
          description: Unknown page title
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'
        503:
          description: A response is unavailable because service queue is busy or full
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problem'
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'
      x-request-handler:
        - get_latest_revision:
            request:
              method: get
              uri: /{domain}/sys/page_revisions/page/{title}
        - get_pdf_from_backend:
            request:
              method: get
              # Hard-coded output options will be replaced later by extending
              # the RESTBase endpoint with additional paramters. Defaults
              # will be A4 and desktop if no parameters are provided.
              uri: '{{options.uri}}/{{domain}}/v1/pdf/{title}/a4'
            return:
              status: 200
              headers:
                # Firefox supports filename*= syntax while Chrome respect
                # filename=. Safari is stupid and understands neither.
                content-disposition: 'attachment; {{filenameParameters(request.params.title)}}'
                content-type: '{{get_pdf_from_backend.headers.content-type}}'
                content-length: '{{get_pdf_from_backend.headers.content-length}}'
                cache-control: '{{default(options.cache_control, "s-maxage=600, max-age=600")}}'
                etag: '{{get_latest_revision.headers.etag}}'
              body: '{{get_pdf_from_backend.body}}'
      x-monitor: false # PDF generation is expensive and it's not stored, so don't run checker script

  /pdf/{title}/{format}:
    x-route-filters:
      <<: *pdf_get_title_filters
    get:
      <<: *pdf_get_title_spec
      parameters:
        - name: title
          in: path
          description: 'Page title. Use underscores instead of spaces. Example: `Main_Page`.'
          required: true
          schema:
            type: string
        - in: path
          name: format
          schema:
            type: string
            enum: ['a4', 'letter', 'legal']
          required: true
          description: PDF format
      x-request-handler:
        - get_latest_revision:
            request:
              method: get
              uri: /{domain}/sys/page_revisions/page/{title}
        - get_pdf_from_backend:
            request:
              method: get
              # Hard-coded output options will be replaced later by extending
              # the RESTBase endpoint with additional paramters. Defaults
              # will be A4 and desktop if no parameters are provided.
              uri: '{{options.uri}}/{{domain}}/v1/pdf/{title}/{format}'
            return:
              status: 200
              headers:
                # Firefox supports filename*= syntax while Chrome respect
                # filename=. Safari is stupid and understands neither.
                content-disposition: 'attachment; {{filenameParameters(request.params.title)}}'
                content-type: '{{get_pdf_from_backend.headers.content-type}}'
                content-length: '{{get_pdf_from_backend.headers.content-length}}'
                cache-control: '{{default(options.cache_control, "s-maxage=600, max-age=600")}}'
                etag: '{{get_latest_revision.headers.etag}}'
              body: '{{get_pdf_from_backend.body}}'
      x-monitor: false # PDF generation is expensive and it's not stored, so don't run checker script

  /pdf/{title}/{format}/{type}:
    x-route-filters:
      <<: *pdf_get_title_filters
    get:
      <<: *pdf_get_title_spec
      parameters:
        - name: title
          in: path
          description: 'Page title. Use underscores instead of spaces. Example: `Main_Page`.'
          required: true
          schema:
            type: string
        - in: path
          name: format
          schema:
            type: string
            enum: ['a4', 'letter', 'legal']
          required: true
          description: PDF format
        - in: path
          name: type
          schema:
            type: string
            enum: ['mobile', 'desktop']
            default: desktop
          description: PDF type - `mobile` (optimized for reading on mobile devices) or `desktop` (regular PDF). `desktop` is the default render mode and it will used if param `type` is not passed
      x-request-handler:
        - get_latest_revision:
            request:
              method: get
              uri: /{domain}/sys/page_revisions/page/{title}
        - get_pdf_from_backend:
            request:
              method: get
              # Hard-coded output options will be replaced later by extending
              # the RESTBase endpoint with additional paramters. Defaults
              # will be A4 and desktop if no parameters are provided.
              uri: '{{options.uri}}/{{domain}}/v1/pdf/{title}/{format}/{type}'
            return:
              status: 200
              headers:
                # Firefox supports filename*= syntax while Chrome respect
                # filename=. Safari is stupid and understands neither.
                content-disposition: 'attachment; {{filenameParameters(request.params.title)}}'
                content-type: '{{get_pdf_from_backend.headers.content-type}}'
                content-length: '{{get_pdf_from_backend.headers.content-length}}'
                cache-control: '{{default(options.cache_control, "s-maxage=600, max-age=600")}}'
                etag: '{{get_latest_revision.headers.etag}}'
              body: '{{get_pdf_from_backend.body}}'
      x-monitor: false # PDF generation is expensive and it's not stored, so don't run checker script
