swagger: '2.0'
info:
  version: '1.0.0-beta'
  title: MediaWiki Summary API
  description: Page content summary API
  termsofservice: https://github.com/wikimedia/restbase#restbase
  contact:
    name: Services
    email: services@lists.wikimedia.org
    url: https://www.mediawiki.org/wiki/Services
  license:
    name: Apache licence, v2
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /summary/{title}:
    x-route-filters:
      - path: ./lib/revision_table_access_check_filter.js
        options:
          redirect_cache_control: '{{options.response_cache_control}}'
    get:
      tags:
        - Page content
      summary: Get a text extract & thumb summary of a page.
      description: |
        The summary response includes a text extract of the first several
        sentences, as well as information about a thumbnail that represents
        the page.

        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)
      produces:
        - application/json
      parameters:
        - name: title
          in: path
          description: "Page title. Use underscores instead of spaces. Example: `Main_Page`."
          type: string
          required: true
        - name: redirect
          in: query
          description: >
            Requests for [redirect pages](https://www.mediawiki.org/wiki/Help:Redirects)
            return HTTP 302 with a redirect target in `Location` header and content in the body.

            To get a 200 response instead, supply `false` to the `redirect` parameter.
          type: boolean
          required: false
      responses:
        '200':
          description: The summary for the given page
          schema:
            $ref: '#/definitions/summary'
          headers:
            ETag:
              description: >
                Syntax: "{revision}/{tid}".
                Example: "701384379/154d7bca-c264-11e5-8c2f-1b51b33b59fc"
        '404':
          description: Unknown page title
          schema:
            $ref: '#/definitions/problem'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'

      x-setup-handler:
        # Set up a simple key-value bucket.
        - init:
            method: 'put'
            uri: /{domain}/sys/key_value/summary
            body:
              valueType: 'json'

      x-request-handler:
        - storage:
            request:
              method: get
              headers:
                cache-control: '{{cache-control}}'
              uri: /{domain}/sys/key_value/summary/{request.params.title}
            catch:
              status: 404
            return_if:
              # Typical case: Return straight from storage.
              status: '2xx'
            return:
              status: 200
              headers:
                content-type: '{{storage.headers.content-type}}'
                etag: '{{storage.headers.etag}}'
                cache-control: '{{options.response_cache_control}}'
              body: '{{storage.body}}'

        # Storage miss. Call the Action API to get the textextract.
        - extract:
            request:
              method: post
              uri: /{domain}/sys/action/query
              body:
                prop: 'info|extracts|pageimages|revisions'
                exsentences: 5
                explaintext: true
                piprop: 'thumbnail'
                pithumbsize: 320
                rvprop: 'timestamp'
                titles: '{{request.params.title}}'
            response:
              # Define the response to save & return.
              headers:
                content-type: application/json
              body:
                title: '{{extract.body.items[0].title}}'
                extract: '{{extract.body.items[0].extract}}'
                thumbnail: '{{httpsSource(extract.body.items[0].thumbnail)}}'
                lang: '{{extract.body.items[0].pagelanguagehtmlcode}}'
                dir: '{{extract.body.items[0].pagelanguagedir}}'
                timestamp: '{{getRevision(extract.body.items[0].revisions).timestamp}}'

        - emit_change_event:
            request:
              method: post
              uri: /{domain}/sys/events/
              body:
                - meta:
                    uri: //{request.params.domain}/api/rest_v1/page/summary/{request.params.title}
          store_and_return:
            request:
              method: put
              uri: /{domain}/sys/key_value/summary/{request.params.title}
              headers: '{{extract.headers}}'
              body: '{{extract.body}}'

            return:
              status: 200
              headers:
                content-type: '{{extract.headers.content-type}}'
                etag: '{{store_and_return.headers.etag}}'
                cache-control: '{{options.response_cache_control}}'
              body: '{{extract.body}}'

      x-monitor: true
      x-amples:
        - title: Get summary from storage
          request:
            params:
              domain: en.wikipedia.org
              title: Barack_Obama
          response:
            status: 200
            headers:
              etag: /.+/
              content-type: /^application\/json$/
            body:
              extract: /.+/
              thumbnail:
                source: /^https:/
              lang: en
              dir: ltr

definitions:
  # A https://tools.ietf.org/html/draft-nottingham-http-problem
  problem:
    required:
      - type
    properties:
      type:
        type: string
      title:
        type: string
      detail:
        type: string
      instance:
        type: string

  summary:
    type: object
    properties:
      title:
        type: string
        description: The page title
      #timestamp:
      #  type: string
      #  format: date-time
      #  description: The ISO timestamp of a page revision
      extract:
        type: string
        description: First several sentences of an article in plain text
      thumbnail:
        type: object
        properties:
          source:
            type: string
            description: Thumbnail image URI
          width:
            type: integer
            description: Thumbnail width
          height:
            type: integer
            description: Thumnail height
        required: ['source', 'width', 'height']
      lang:
        type: string
        description: The page language code
        example: en
      dir:
        type: string
        description: The page language direction code
        example: ltr
      timestamp:
        type: string
        description: The time when the page was last editted in the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format
        example: '1970-01-01T00:00:00.000Z'
    required: ['title', 'extract', 'lang', 'dir']
