swagger: '2.0'
info:
  version: '1.0.0-beta'
  title: MediaWiki Summary API
  description: Page content summary API
  termsofservice: https://github.com/wikimedia/restbase#restbase
  contact:
    name: Services
    email: services@lists.wikimedia.org
    url: https://www.mediawiki.org/wiki/Services
  license:
    name: Apache licence, v2
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /summary/{title}:
    get:
      tags:
        - Page content
      description: >
        Returns the summary of the latest page content available in storage.
        Currently the summary includes the text for the first several sentences and
        the thumbnail URL.

        Provide a `Cache-Control: no-cache` header to request the latest data.

        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)
      produces:
        - application/json
      parameters:
        - name: title
          in: path
          description: The page title.
          type: string
          required: true
      responses:
        '200':
          description: The summary for the given page
          schema:
            $ref: '#/definitions/summary'
        '404':
          description: Unknown page title
          schema:
            $ref: '#/definitions/problem'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'

      x-setup-handler:
        # Set up a simple key-value bucket.
        - init:
            method: 'put'
            uri: /{domain}/sys/key_value/summary
            body:
              valueType: 'json'

      x-request-handler:

        # Get the revision metadata for access control (will return an error
        # if there's no access), and so that we can use the normalized title &
        # other info in case we have a storage miss.
        - rev_info:
            request:
              method: get
              uri: /{domain}/sys/page_revisions/page/{title}
            response:
              body: '{{rev_info.body.items[0]}}'

          storage:
            request:
              method: get
              headers:
                cache-control: '{{cache-control}}'
              uri: /{domain}/sys/key_value/summary/{request.params.title}
            catch:
              status: 404
            return_if:
              # Typical case: Return straight from storage.
              status: '2xx'
            return:
              status: 200
              headers:
                content-type: '{{storage.headers.content-type}}'
                etag: '{{storage.headers.etag}}'
                cache-control: '{{options.response_cache-control}}'
              body: '{{storage.body}}'

        # Storage miss. Call the Action API to get the textextract.
        - extract:
            request:
              method: post
              uri: /{domain}/sys/action/query
              body:
                prop: 'info|extracts|pageimages'
                redirects: true
                exsentences: 5
                explaintext: true
                piprop: 'thumbnail'
                pithumbsize: 320
                titles: '{{rev_info.body.title}}'
            response:
              # Define the response to save & return.
              headers:
                content-type: application/json
              body:
                title: '{{extract.body.items[0].title}}'
                extract: '{{extract.body.items[0].extract}}'
                thumbnail: '{{httpsSource(extract.body.items[0].thumbnail)}}'
                lang: '{{extract.body.items[0].pagelanguagehtmlcode}}'
                dir: '{{extract.body.items[0].pagelanguagedir}}'
                # Need to figure out the format of this before we can add it.
                # See https://phabricator.wikimedia.org/T117082#1787617.
                #timestamp: '{{request.params.timestamp}}'

        - store_and_return:
            request:
              method: put
              uri: /{domain}/sys/key_value/summary/{request.params.title}
              headers: '{{extract.headers}}'
              body: '{{extract.body}}'

            return:
              status: 200
              headers:
                content-type: '{{extract.headers.content-type}}'
                etag: '{{store_and_return.headers.etag}}'
                cache-control: '{{options.response_cache-control}}'
              body: '{{extract.body}}'

      x-monitor: true
      x-amples:
        - title: Get summary from storage
          request:
            params:
              domain: en.wikipedia.org
              title: Barack_Obama
          response:
            status: 200
            headers:
              etag: /.+/
              content-type: /^application\/json$/
            body:
              extract: /.+/
              thumbnail:
                source: /^https:/
              lang: en
              dir: ltr

definitions:
  # A https://tools.ietf.org/html/draft-nottingham-http-problem
  problem:
    required:
      - type
    properties:
      type:
        type: string
      title:
        type: string
      detail:
        type: string
      instance:
        type: string

  summary:
    type: object
    properties:
      title:
        type: string
        description: The page title
      #timestamp:
      #  type: string
      #  format: date-time
      #  description: The ISO timestamp of a page revision
      extract:
        type: string
        description: First several sentences of an article in plain text
      thumbnail:
        type: object
        properties:
          source:
            type: string
            description: Thumbnail image URI
          width:
            type: integer
            description: Thumbnail width
          height:
            type: integer
            description: Thumnail height
        required: ['source', 'width', 'height']
      lang:
        type: string
        description: The page language code
        example: en
      dir:
        type: string
        description: The page language direction code
        example: ltr
    required: ['title', 'extract', 'lang', 'dir']
