openapi: 3.0.1
info:
  version: 1.0.0-beta
  title: MediaWiki page media API
  description: API for retrieving data about media items appearing on a given page
  termsOfService: https://www.mediawiki.org/wiki/REST_API#Terms_and_conditions
  contact:
    name: Reading Infrastructure
    url: https://www.mediawiki.org/wiki/Wikimedia_Reading_Infrastructure_team
  license:
    name: Apache licence, v2
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /media-list/{title}:
    x-route-filters:
      - path: ./lib/access_check_filter.js
        options:
          redirect_cache_control: '{{options.response_cache_control}}'
      - path: lib/security_response_header_filter.js
      - path: lib/language_variants_filter.js
    get: &media_list_title_get_spec
      tags:
        - Page content
      summary: Get list of media files used on a page.
      description: |
        Gets the list of media items (images, audio, and video) in the order in which they appear on a
        given wiki page.

        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)
      parameters:
        - name: title
          in: path
          description: 'Page title. Use underscores instead of spaces. Example: `Main_Page`.'
          required: true
          schema:
            type: string
        - name: redirect
          in: query
          description: |
            Requests for [redirect pages](https://www.mediawiki.org/wiki/Help:Redirects) return HTTP 302 with a redirect target in `Location` header and content in the body.
            To get a 200 response instead, supply `false` to the `redirect` parameter.
          schema:
            type: boolean
      responses:
        200:
          description: JSON containing metadata of media items appearing on the given
            page.
          headers:
            ETag:
              description: |
                Syntax: "{revision}/{tid}". Example: "701384379/154d7bca-c264-11e5-8c2f-1b51b33b59fc"
              schema:
                type: string
          content:
            application/json; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/Media/1.3.1":
              schema:
                $ref: '#/components/schemas/media_list'
        301:
          description: |
            A permanent redirect is returned if the supplied article title was not in the normalized form.
            To avoid this kind of redirect, you can use the [mediawiki-title](https://github.com/wikimedia/mediawiki-title) library to perform
            title normalization client-side.

            Beware that redirected pre-flighted cross-origin requests (such as those sending custom request headers like `Api-User-Agent`)
            will fail in most current browsers [due to a spec bug](https://github.com/whatwg/fetch/issues/204).
        302:
          description: |
            The page is a [redirect page](https://www.mediawiki.org/wiki/Help:Redirects).
            The `location` header points to the redirect target.
            If you would like to avoid automatically following redirect pages, set the `redirect=false` query parameter.

            Beware that redirected pre-flighted cross-origin requests (such as those sending custom request headers like `Api-User-Agent`)
            will fail in most current browsers [due to a spec bug](https://github.com/whatwg/fetch/issues/204).
        404:
          description: Unknown page title
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'
      operationId: getContent-media-list
      x-monitor: true
      x-amples:
        - title: Get media-list from storage
          request:
            params:
              domain: en.wikipedia.org
              title: User:BSitzmann_(WMF)/MCS/Test/Frankenstein
          response:
            status: 200
            headers:
              etag: /.+/
              content-type: /^application\/json/
            body:
              revision: /\d+/
              tid: /.+/
              items:
                - type: /.+/
                  section_id: /\d+/
                  showInGallery: /.+/

  /media-list/{title}/{revision}:
    get:
      <<: *media_list_title_get_spec
      parameters:
        - name: title
          in: path
          description: 'Page title. Use underscores instead of spaces. Example: `Main_Page`.'
          required: true
          schema:
            type: string
        - name: revision
          in: path
          description: |
            Optional page revision. Note that older revisions are not stored, so request latency with the revision would be higher.
          required: true
          schema:
            type: integer
        - name: redirect
          in: query
          description: |
            Requests for [redirect pages](https://www.mediawiki.org/wiki/Help:Redirects) return HTTP 302 with a redirect target in `Location` header and content in the body.
            To get a 200 response instead, supply `false` to the `redirect` parameter.
          schema:
            type: boolean
      operationId: getContentWithRevision-media-list
      x-monitor: false

components:
  schemas:
    titles_set:
      type: object
      properties:
        canonical:
          type: string
          description: the DB key (non-prefixed)
        normalized:
          type: string
          description: the normalized title (https://www.mediawiki.org/wiki/API:Query#Title_normalization)
        display:
          type: string
          description: the title as it should be displayed to the user
      required:
        - canonical
        - normalized
        - display

    media_list:
      type: object
      properties:
        revision:
          type: string
          description: the revision ID used to create the list
        tid:
          type: string
          description: the time uuid of the page rendering used to create the list
        items:
          type: array
          description: a list of media items
          items:
            $ref: '#/components/schemas/media_item'
      required:
        - items
        - revision
        - tid

    media_item:
      type: object
      properties:
        title:
          type: string
          description: The file page title
        type:
          type: string
          enum:
            - image
            - video
            - audio
        section_id:
          type: integer
          description: section ID in which the item is found on the page
        showInGallery:
          type: boolean
          description: whether the client should show the file in an image gallery presentation
        caption:
          type: object
          properties:
            html:
              type: string
              description: on-wiki caption for the media item, including all HTML markup
            text:
              type: string
              description: plain text of the on-wiki caption for the media item
        original:
          type: object
          description: reference to a Mathoid-rendered math formula image
          properties:
            source:
              type: string
              description: Mathoid image render URL
            mime:
              type: string
              description: the Mathoid image mime type
      required:
        - type
        - section_id
        - showInGallery
