swagger: '2.0'
info:
  version: '1.0.0'
  title: RESTBase key-value module
  description: >
    Blob storage with HTTP interface, backed by table storage.
    It only accepts serialized binary data as `application/octet-stream`
    All the headers, prefixed with `x-store-` are stored and upon response
    returned without the prefix. It's expected that the client will provide
    a meaningful `etag` header upon storing the content, otherwise it will be
    generated as a hash of the content.
paths:
  /{bucket}:
    put:
      operationId: createBucket

  /{bucket}/{key}:
    get:
      operationId: getRevision
    put:
      operationId: putRevision

  /{bucket}/{key}/:
    get:
      operationId: listRevisions
