swagger: 2.0
info:
  version: 0.1.0
  title: Internal Parsoid content API
  description: Access Parsoid-generated wikitext, html and metadata.
    Transparently generates missing content and interfaces with the MediaWiki
    API through the `action` module.
paths:

  /pagebundle/{title}: &pagebundle_title
    get:
      summary: Retrieve a JSON bundle containing html and data-parsoid
      operationId: getPageBundle
    post:
      summary: Retrieve a JSON bundle containing html and data-parsoid
      operationId: getPageBundle

  /pagebundle/{title}/{revision}:
    <<: *pagebundle_title

  /pagebundle/{title}/{revision}/{tid}:
    <<: *pagebundle_title

  /wikitext/{title}: &wikitext_title
    get:
      summary: Retrieve the wikitext for a title and revision.
      operationId: getWikitext

  /wikitext/{title}/{revision}:
    <<: *wikitext_title

  /wikitext/{title}/{revision}/{tid}:
    <<: *wikitext_title

  /html/{title}: &html_title
    get:
      summary: Retrieve the HTML for title and revision.
      operationId: getHtml

  /html/{title}/{revision}:
    <<: *html_title

  /html/{title}/{revision}/{tid}:
    <<: *html_title

  /data-parsoid/{title}: &data-parsoid_title
    get:
      summary: Retrieve the data-parsoid JSON for title & revision.
      operationId: getDataParsoid

  /data-parsoid/{title}/{revision}:
    <<: *data-parsoid_title

  /data-parsoid/{title}/{revision}/{tid}:
    <<: *data-parsoid_title

  /lint/{title}: &lint_title
    get:
      summary: Retreive the lint errors for a specific page revision
      operationId: getLintErrors

  /lint/{title}/{revision}:
    <<: *lint_title

  /transform/html/to/html: &transform_html_to_html
    post:
      summary: Update HTML, while optionally passing in title & revision.
      operationId: transformHtmlToHtml

  /transform/html/to/html/{title}:
    <<: *transform_html_to_html

  /transform/html/to/html/{title}/{revision}:
    <<: *transform_html_to_html

  /transform/html/to/wikitext: &transform_html_to_wikitext
    post:
      summary: Transform HTML to wikitext.
      operationId: transformHtmlToWikitext

  /transform/html/to/wikitext/{title}:
    <<: *transform_html_to_wikitext

  /transform/html/to/wikitext/{title}/{revision}:
    <<: *transform_html_to_wikitext

  /transform/wikitext/to/html: &transform_wikitext_to_html
    post:
      summary: Transform wikitext to HTML.
      operationId: transformWikitextToHtml

  /transform/wikitext/to/html/{title}:
    <<: *transform_wikitext_to_html

  /transform/wikitext/to/html/{title}/{revision}:
    <<: *transform_wikitext_to_html

  /transform/wikitext/to/lint: &transform_wikitext_to_lint
    post:
      summary: Check the wikitext for lint errors.
      operationId: transformWikitextToLint

  /transform/wikitext/to/lint/{title}:
    <<: *transform_wikitext_to_lint

  /transform/wikitext/to/lint/{title}/{revision}:
    <<: *transform_wikitext_to_lint

  /transform/changes/to/wikitext/{title}/{revision}:
    post:
      summary: Transform section changes to wikitext.
      operationId: transformChangesToWikitext
