swagger: 2.0
info:
  version: 0.1.0
  title: Internal Parsoid content API
  description: Access Parsoid-generated wikitext, html and metadata.
    Transparently generates missing content and interfaces with the MediaWiki
    API through the `action` module.
paths:

  /pagebundle/{title}{/revision}{/tid}:
    get:
      summary: Retrieve a JSON bundle containing html and data-parsoid
      operationId: getPageBundle
    post:
      summary: Retrieve a JSON bundle containing html and data-parsoid
      operationId: getPageBundle

  /wikitext/{title}/:
    get:
      summary: List Wikitext revisions.
      operationId: listWikitextRevisions
      parameters:
        - name: page
          in: query
          description: The next page token
          type: string
          required: false

  /wikitext/{title}{/revision}{/tid}:
    get:
      summary: Retrieve the wikitext for a title and revision.
      operationId: getWikitext

  /html/{title}/:
    get:
      summary: List HTML revisions.
      operationId: listHtmlRevisions
      parameters:
        - name: page
          in: query
          description: The next page token
          type: string
          required: false

  /html/{title}{/revision}{/tid}:
    get:
      summary: Retrieve the HTML for title and revision.
      operationId: getHtml

  /data-parsoid/{title}/:
    get:
      summary: List data-parsoid revisions.
      operationId: listDataParsoidRevisions
      parameters:
        - name: page
          in: query
          description: The next page token
          type: string
          required: false

  /data-parsoid/{title}{/revision}{/tid}:
    get:
      summary: Retrieve the data-parsoid JSON for title & revision.
      operationId: getDataParsoid

  /transform/html/to/html{/title}{/revision}:
    post:
      summary: Update HTML, while optionally passing in title & revision.
      operationId: transformHtmlToHtml

  /transform/html/to/wikitext{/title}{/revision}:
    post:
      summary: Transform HTML to wikitext.
      operationId: transformHtmlToWikitext

  /transform/wikitext/to/html{/title}{/revision}:
    post:
      summary: Transform wikitext to HTML.
      operationId: transformWikitextToHtml

  /transform/wikitext/to/lint{/title}{/revision}:
    post:
      summary: Check the wikitext for lint errors.
      operationId: transformWikitextToLint

  /transform/changes/to/wikitext/{title}/{revision}:
    post:
      summary: Transform section changes to wikitext.
      operationId: transformChangesToWikitext
