general:
  buildTool: mta
  deployMode: direct
  cloudService: cpi

steps:
  cpiDeploy:
    host: 'https://dev-sa-wm0yvk1u.integrationsuite-trial01.cfapps.us10-001.hana.ondemand.com'
    username: 'praymohanty@teksystems.com'
    password: 'Vitiksha*098Chunu'
    integrationFlowId: 'Demotest'
    integrationPackageId: 'xml_TO_csv'
