swagger: '2.0'
info:
  title: Mathoid sys API module
paths:
  /request/{format}:
    post:
      x-request-handler:
        - store:
            request:
              method: put
              uri: /{domain}/sys/post_data/mathoid.request/
              body:
                q: '{$.request.body.q}'
                type: '{$$.default($.request.body.type, "tex")}'
        - handle_req:
            request:
              method: post
              uri: /{domain}/sys/mathoid/v1/handler/{format}
              headers:
                cache-control: '{cache-control}'
                x-resource-location: '{$.store.body}'
              body:
                q: '{$.request.body.q}'
                type: '{$$.default($.request.body.type, "tex")}'
  /request/{format}/{hash}:
    get:
      x-setup-handler:
        - init:
            uri: /{domain}/sys/post_data/mathoid.request
      x-request-handler:
        - get_from_storage:
            request:
              method: get
              uri: /{domain}/sys/post_data/mathoid.request/{hash}
        - handle_req:
            request:
              method: post
              uri: /{domain}/sys/mathoid/v1/handler/{format}
              headers:
                cache-control: '{cache-control}'
                x-resource-location: '{$.request.params.hash}'
              body: '{$.get_from_storage.body}'
  /handler/{format}:
    post:
      x-setup-handler:
        - init:
            uri: /{domain}/sys/key_value/mathoid.data
            body:
              keyType: string
              valueType: json
      x-request-handler:
        - check_storage:
            request:
              method: get
              uri: /{domain}/sys/key_value/mathoid.data/{$.request.headers.x-resource-location}
              headers:
                cache-control: '{cache-control}'
            return_if:
              status: '2xx'
            return:
              status: 200
              headers: '{$$.merge($.check_storage.body.data[$.request.params.format].headers,$.check_storage.body.headers)}'
              body: '{$.check_storage.body.data[$.request.params.format].body}'
            catch:
              status: 404
        - mathoid:
            request:
              method: post
              uri: {{ service_uri.mathoid }}/complete
              body:
                q: '{$.request.body.q}'
                type: '{$.request.body.type}'
        - store:
            request:
              method: put
              uri: /{domain}/sys/key_value/mathoid.data/{$.request.headers.x-resource-location}
              headers:
                content-type: application/json
              body:
                headers: '{$$.merge($$.strip($.mathoid.headers, ["content-length", "content-encoding"]), {"x-resource-location": $.request.headers.x-resource-location})}'
                data: '{$.mathoid.body}'
            return:
              status: 200
              headers: '{$$.merge($.mathoid.body[$.request.params.format].headers,$$.merge($$.strip($.mathoid.headers, ["content-length", "content-encoding"]), {"x-resource-location": $.request.headers.x-resource-location}))}'
              body: '{$.mathoid.body[$.request.params.format].body}'

