swagger: '2.0'
info:
  version: '0.0.1'
  title: RESTBase table storage interface
  description: Generic table storage interface optimized for distributed backends 
paths:
#  /{table}:
#    put:
#      operationId: createTable
#    delete:
#      operationId: dropTable
#
#  /{table}/:
#    get: &get
#      operationId: get
#    post: *get
#    put:
#      operationId: put
#
#  /{table}/{+rest}:
#    get:
#      operationId: get
#    put:
#      operationId: put
